In [ ]:
import pandas as pd
import json

In [ ]:
fpath = "/content/drive/MyDrive/Start Hackaton Datasets/for_json/Santa Rosa Monthly Water Consumption.xlsx"
df = pd.read_excel(fpath)

In [ ]:
df

         Date  Monthly Water Consumption (in cubic meters)    Barangay
0  2016-01-31                                 1.597128e+08  Santa Rosa
1  2016-02-29                                 1.197846e+08  Santa Rosa
2  2016-03-31                                 1.796769e+08  Santa Rosa
3  2016-04-30                                 1.397487e+08  Santa Rosa
4  2016-05-31                                 1.597128e+08  Santa Rosa
5  2016-06-30                                 1.597128e+08  Santa Rosa
6  2016-07-31                                 1.597128e+08  Santa Rosa
7  2016-08-31                                 7.985640e+07  Santa Rosa
8  2016-09-30                                 3.593538e+08  Santa Rosa
9  2016-10-31                                 9.982050e+07  Santa Rosa
10 2016-11-30                                 7.985640e+07  Santa Rosa
11 2016-12-31                                 2.994615e+08  Santa Rosa
12 2017-01-31                                 1.659264e+08  Santa Rosa
13 2017-02-28                                 1.244448e+08  Santa Rosa
14 2017-03-31                                 1.866672e+08  Santa Rosa
15 2017-04-30                                 1.451856e+08  Santa Rosa
16 2017-05-31                                 1.659264e+08  Santa Rosa
17 2017-06-30                                 1.659264e+08  Santa Rosa
18 2017-07-31                                 1.659264e+08  Santa Rosa
19 2017-08-31                                 1.659264e+08  Santa Rosa
20 2017-09-30                                 2.903712e+08  Santa Rosa
21 2017-10-31                                 1.037040e+08  Santa Rosa
22 2017-11-30                                 8.296320e+07  Santa Rosa
23 2017-12-31                                 3.111120e+08  Santa Rosa
24 2018-01-31                                 1.773760e+08  Santa Rosa
25 2018-02-28                                 1.330320e+08  Santa Rosa
26 2018-03-31                                 1.995480e+08  Santa Rosa
27 2018-04-30                                 1.552040e+08  Santa Rosa
28 2018-05-31                                 1.773760e+08  Santa Rosa
29 2018-06-30                                 1.773760e+08  Santa Rosa
30 2018-07-31                                 1.773760e+08  Santa Rosa
31 2018-08-31                                 1.552040e+08  Santa Rosa
32 2018-09-30                                 3.547520e+08  Santa Rosa
33 2018-10-31                                 8.868800e+07  Santa Rosa
34 2018-11-30                                 8.868800e+07  Santa Rosa
35 2018-12-31                                 3.325800e+08  Santa Rosa
36 2019-01-31                                 1.175665e+08  Santa Rosa
37 2019-02-28                                 1.410798e+08  Santa Rosa
38 2019-03-31                                 2.116197e+08  Santa Rosa
39 2019-04-30                                 1.645931e+08  Santa Rosa
40 2019-05-31                                 1.881064e+08  Santa Rosa
41 2019-06-30                                 1.175665e+08  Santa Rosa
42 2019-07-31                                 1.175665e+08  Santa Rosa
43 2019-08-31                                 1.645931e+08  Santa Rosa
44 2019-09-30                                 5.878325e+08  Santa Rosa
45 2019-10-31                                 9.405320e+07  Santa Rosa
46 2019-11-30                                 9.405320e+07  Santa Rosa
47 2019-12-31                                 3.526995e+08  Santa Rosa
48 2020-01-31                                 1.466730e+08  Santa Rosa
49 2020-02-29                                 1.466730e+08  Santa Rosa
50 2020-03-31                                 2.200095e+08  Santa Rosa
51 2020-04-30                                 1.711185e+08  Santa Rosa
52 2020-05-31                                 1.955640e+08  Santa Rosa
53 2020-06-30                                 1.466730e+08  Santa Rosa
54 2020-07-31                                 1.466730e+08  Santa Rosa
55 2020-08-31                                 1.466730e+08  Santa Rosa
56 2020-09-30                                 5.378010e+08  Santa Rosa
57 2020-10-31                                 1.222275e+08  Santa Rosa
58 2020-11-30                                 9.778200e+07  Santa Rosa
59 2020-12-31                                 3.666825e+08  Santa Rosa

In [ ]:
result = df.to_json(orient="table")
parsed = json.loads(result)

json_object = json.dumps(parsed, indent=4)

In [ ]:
with open("santa_rosa.json", "w") as outfile:
    json.dump(parsed, outfile)